// Historical NFFFFL data imported from Yahoo Fantasy screenshots.
// Only include facts directly supported by the archived source.
// Playoff finishes/champion fields should remain null until a playoff bracket
// or other reliable season-final source is provided.

export const yahooHistory = [
  {
    season: 2025,
    platform: 'Yahoo',
    sourceType: 'standings-screenshot',
    notes: 'Regular-season standings snapshot. Yahoo displayed final standings update: Thu Jan 08 02:53am EST.',
    champion: null,
    runnerUp: null,
    teams: [
      {
        rank: 1,
        teamName: 'The .08ers',
        division: 'Trap House',
        wins: 14,
        losses: 0,
        ties: 0,
        divisionWins: 6,
        divisionLosses: 0,
        divisionTies: 0,
        pointsFor: 1850.44,
        pointsAgainst: 1286.60,
        streak: 'W-14',
        waiverPriority: 11,
        moves: 36,
        clinchedPlayoffSpot: true,
      },
      {
        rank: 2,
        teamName: 'Krazy Kams',
        division: '3209',
        wins: 7,
        losses: 7,
        ties: 0,
        divisionWins: 4,
        divisionLosses: 2,
        divisionTies: 0,
        pointsFor: 1567.86,
        pointsAgainst: 1531.74,
        streak: 'W-1',
        waiverPriority: 2,
        moves: 15,
        clinchedPlayoffSpot: true,
      },
      {
        rank: 3,
        teamName: 'Push it to the limit',
        division: '3209',
        wins: 6,
        losses: 8,
        ties: 0,
        divisionWins: 4,
        divisionLosses: 2,
        divisionTies: 0,
        pointsFor: 1532.78,
        pointsAgainst: 1595.46,
        streak: 'W-4',
        waiverPriority: 3,
        moves: 10,
        clinchedPlayoffSpot: true,
      },
      {
        rank: 4,
        teamName: 'The Sheriff',
        division: '3209',
        wins: 9,
        losses: 5,
        ties: 0,
        divisionWins: 4,
        divisionLosses: 2,
        divisionTies: 0,
        pointsFor: 1551.74,
        pointsAgainst: 1450.14,
        streak: 'L-1',
        waiverPriority: 7,
        moves: 35,
        clinchedPlayoffSpot: true,
      },
      {
        rank: 5,
        teamName: 'The Redskins',
        division: 'Trap House',
        wins: 10,
        losses: 4,
        ties: 0,
        divisionWins: 3,
        divisionLosses: 3,
        divisionTies: 0,
        pointsFor: 1713.16,
        pointsAgainst: 1484.40,
        streak: 'L-1',
        waiverPriority: 1,
        moves: 67,
        clinchedPlayoffSpot: false,
      },
      {
        rank: 6,
        teamName: 'Death By Kicker',
        division: 'Kaspers & Dads',
        wins: 7,
        losses: 7,
        ties: 0,
        divisionWins: 4,
        divisionLosses: 2,
        divisionTies: 0,
        pointsFor: 1498.16,
        pointsAgainst: 1519.18,
        streak: 'W-3',
        waiverPriority: 9,
        moves: 48,
        clinchedPlayoffSpot: true,
      },
      {
        rank: 7,
        teamName: "Mr. Robinson's Hood",
        division: 'Kaspers & Dads',
        wins: 6,
        losses: 8,
        ties: 0,
        divisionWins: 3,
        divisionLosses: 3,
        divisionTies: 0,
        pointsFor: 1537.80,
        pointsAgainst: 1607.22,
        streak: 'L-1',
        waiverPriority: 8,
        moves: 39,
        clinchedPlayoffSpot: true,
      },
      {
        rank: 8,
        teamName: 'Baby Back Gibbs',
        division: 'Trap House',
        wins: 6,
        losses: 8,
        ties: 0,
        divisionWins: 1,
        divisionLosses: 5,
        divisionTies: 0,
        pointsFor: 1465.98,
        pointsAgainst: 1561.92,
        streak: 'W-1',
        waiverPriority: 4,
        moves: 13,
        clinchedPlayoffSpot: false,
      },
      {
        rank: 9,
        teamName: 'I ❤️ 🪽',
        division: 'Kaspers & Dads',
        wins: 5,
        losses: 9,
        ties: 0,
        divisionWins: 2,
        divisionLosses: 4,
        divisionTies: 0,
        pointsFor: 1491.02,
        pointsAgainst: 1661.00,
        streak: 'L-2',
        waiverPriority: 12,
        moves: 9,
        clinchedPlayoffSpot: false,
      },
      {
        rank: 10,
        teamName: 'The Skattebo Express',
        division: 'Kaspers & Dads',
        wins: 5,
        losses: 9,
        ties: 0,
        divisionWins: 3,
        divisionLosses: 3,
        divisionTies: 0,
        pointsFor: 1451.50,
        pointsAgainst: 1509.04,
        streak: 'W-1',
        waiverPriority: 10,
        moves: 29,
        clinchedPlayoffSpot: false,
      },
      {
        rank: 11,
        teamName: "I just hope I'm not last place",
        division: 'Trap House',
        wins: 5,
        losses: 9,
        ties: 0,
        divisionWins: 2,
        divisionLosses: 4,
        divisionTies: 0,
        pointsFor: 1282.66,
        pointsAgainst: 1587.34,
        streak: 'L-2',
        waiverPriority: 5,
        moves: 22,
        clinchedPlayoffSpot: false,
      },
      {
        rank: 12,
        teamName: 'NoT mY roYal subJects',
        division: '3209',
        wins: 4,
        losses: 10,
        ties: 0,
        divisionWins: 0,
        divisionLosses: 6,
        divisionTies: 0,
        pointsFor: 1447.38,
        pointsAgainst: 1596.44,
        streak: 'L-3',
        waiverPriority: 6,
        moves: 22,
        clinchedPlayoffSpot: false,
      },
    ],
  },
];

export const getYahooSeason = (season) => yahooHistory.find((entry) => entry.season === Number(season));
